# -*- coding: utf-8 -*-
"""zoo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11omuWPFYeP7qQWx8yyJadnM7wm4KyLXV
"""

def hours():
  print("Open 9-5 daily")

